マイクロポストの削除後に復活できるようにする #14
NaCl-Ltd/intern-2024-B pull request #42
Opened 2024-09-10 07:07 UTC by j2132Matutani

・削除を押すと通常のマイクロポスト一覧には表示されなくなり、削除ページにのみ表示
・削除されたポストには削除取消を表示
・削除取消を押すと通常のマイクロポスト一覧に表示
![スクリーンショット 2024-09-10 160334](https://github.com/user-attachments/assets/a1f16317-095f-4833-9278-395aa940bd41)
![スクリーンショット 2024-09-10 160409](https://github.com/user-attachments/assets/d386e4a8-91d9-4305-ac9b-4a263b4b324b)
![スクリーンショット 2024-09-10 160732](https://github.com/user-attachments/assets/73a84f4c-f883-41b8-87d0-a3b367d55e03)

2024-09-10 07:39 UTC, skeleton1998 requested changes
簡単にですが、レビューさせて頂きました。ご確認お願いします。

2024-09-10 07:39 UTC, skeleton1998 commented on app/controllers/users_controller.rb
> +    @microposts = @user.microposts.paginate(page: params[:page]).where(deleted_at: nil)
`microposts.where().paginate()` でないと、1ページに表示されるマイクロポスト数が削除されたマイクロポストも含んでしまうので、ページごとに数がバラバラになるかもしれません。

2024-09-10 07:39 UTC, skeleton1998 commented on app/controllers/static_pages_controller.rb
> +      @feed_items = current_user.feed.limit(10).where(deleted_at: nil)
ページネーションと同様に、microposts.where().limitでないと削除された数に影響を受けます。

2024-09-10 07:39 UTC, skeleton1998 commented on app/controllers/static_pages_controller.rb
> +      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 10).where(deleted_at: nil)
ユーザコントローラのpaginateと同様にwhereが後では、ページごとの数に影響がありそうです。

2024-09-10 07:39 UTC, skeleton1998 commented on app/controllers/static_pages_controller.rb
> +      @microposts = current_user.microposts.paginate(page: params[:page]).where.not(deleted_at: nil)
こちらも削除されたマイクロポストの数がページごとにばらばらになりそうです。

2024-09-10 07:41 UTC, keitakishino approved these changes

2024-09-10 07:41 UTC, keitakishino commented on app/views/microposts/_micropost.html.erb
> +        <%= link_to '削除取消',recover_micropost_path(micropost), data:{"turbo-method": :post} %>
せっかくなので多言語化してあるとより良いです！

2024-09-10 07:41 UTC, keitakishino commented on storage/pw/do/pwdol7jov11yj4no0get4z3kekcw
なんかごみついてます？

2024-09-10 07:41 UTC, keitakishino commented on app/controllers/static_pages_controller.rb
> +      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 10).where(deleted_at: nil)
複数回使うモデルのクラスメソッド（.whereとか.orderとか）はscopeでまとめることができます！

https://railsguides.jp/active_record_querying.html#active-record%E3%82%AF%E3%82%A8%E3%83%AA%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%95%E3%82%A7%E3%82%A4%E3%82%B9%E3%81%A8%E3%81%AF%EF%BC%9F

-------
今回の場合はこんな感じに指定する感じですかね（scope名は適当です）

```ruby
# app/models/micropost.rb
scope :exist_records, -> { where(deleted_at: nil) }

# app/controllers/static_pages_controller.rb
@feed_items = current_user.feed.paginate(page: params[:page], per_page: 10).exist_records
```

2024-09-11 01:27 UTC, keitakishino approved these changes

2024-09-11 01:32 UTC, merged